### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TommyLike**
Used to test the prow system

### CODE REVIEW

**Comment by TommyLike** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindspore-ai/infrastructure/pull/3#" title="Author self-approved">TommyLike</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindspore-ai%2Finfrastructure).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/mindspore-ai/infrastructure/blob/master/OWNERS)~~ [TommyLike]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by TommyLike** [comment]
@TommyLike: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/mindspore-ai/infrastructure/pull/3#issuecomment-569163856):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by TommyLike** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindspore-ai/infrastructure/pull/3#issuecomment-569164054" title="Approved">leonwanghui</a>*, *<a href="https://github.com/mindspore-ai/infrastructure/pull/3#" title="Author self-approved">TommyLike</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindspore-ai%2Finfrastructure).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/mindspore-ai/infrastructure/blob/master/OWNERS)~~ [TommyLike,leonwanghui]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by leonwanghui — APPROVED** [review]
LGTM

**Pull request merged**
